name: ha_alarm
description: Home Assistant Alarm Control
publish_to: none
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  dio: ^5.4.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0f172a"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
